# Config Parameters that need to be set for training
# moved out from the implementation here 
# https://github.com/SongweiGe/TATS/blob/main/tats/tats_vqgan.py
# to make the training parameters a bit easier to spot & modify
    @staticmethod
    def add_model_specific_args(parent_parser):
        parser = argparse.ArgumentParser(parents=[parent_parser], add_help=False)
        parser.add_argument('--embedding_dim', type=int, default=256)
        parser.add_argument('--n_codes', type=int, default=2048)
        parser.add_argument('--n_hiddens', type=int, default=240)
        parser.add_argument('--lr', type=float, default=3e-4)
        parser.add_argument('--downsample', nargs='+', type=int, default=(4, 4, 4))
        parser.add_argument('--disc_channels', type=int, default=64)
        parser.add_argument('--disc_layers', type=int, default=3)
        parser.add_argument('--discriminator_iter_start', type=int, default=50000)
        parser.add_argument('--disc_loss_type', type=str, default='hinge', choices=['hinge', 'vanilla'])
        parser.add_argument('--image_gan_weight', type=float, default=1.0)
        parser.add_argument('--video_gan_weight', type=float, default=1.0)
        parser.add_argument('--l1_weight', type=float, default=4.0)
        parser.add_argument('--gan_feat_weight', type=float, default=0.0)
        parser.add_argument('--perceptual_weight', type=float, default=0.0)
        parser.add_argument('--i3d_feat', action='store_true')
        parser.add_argument('--restart_thres', type=float, default=1.0)
        parser.add_argument('--no_random_restart', action='store_true')
        parser.add_argument('--norm_type', type=str, default='group', choices=['batch', 'group'])
        parser.add_argument('--padding_type', type=str, default='replicate', choices=['replicate', 'constant', 'reflect', 'circular'])

        return parser

# Config parameters from the medicaldiffuion repo  
seed: 1234
batch_size: 30
num_workers: 30

gpus: 1
accumulate_grad_batches: 1
default_root_dir: /data/home/firas/Desktop/work/other_groups/medicaldiffusion/checkpoints/vq_gan/
default_root_dir_postfix: ''
resume_from_checkpoint:
max_steps: -1
max_epochs: -1
precision: 16
gradient_clip_val: 1.0


embedding_dim: 256
n_codes: 2048
n_hiddens: 240
lr: 3e-4
downsample: [4, 4, 4]
disc_channels: 64
disc_layers: 3
discriminator_iter_start: 50000
disc_loss_type: hinge
image_gan_weight: 1.0
video_gan_weight: 1.0
l1_weight: 4.0
gan_feat_weight: 0.0
perceptual_weight: 0.0
i3d_feat: False
restart_thres: 1.0
no_random_restart: False
norm_type: group
padding_type: replicate
num_groups: 32